/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISouSwap, ISouSwapInterface } from "../ISouSwap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "input_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "input_reserve",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "output_reserve",
        type: "uint256",
      },
    ],
    name: "getInputPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class ISouSwap__factory {
  static readonly abi = _abi;
  static createInterface(): ISouSwapInterface {
    return new utils.Interface(_abi) as ISouSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISouSwap {
    return new Contract(address, _abi, signerOrProvider) as ISouSwap;
  }
}
